version: '3'
services:
  db:
    container_name: pgdb
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  web:
    build: .
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    ports:
      - "4000:4000"
    depends_on:
      - db
volumes:
  pgdata:
