version: '3'
services:
  db:
    container_name: pgdb
    restart: always
    image: postgres:latest
    ports:
      - ${DB_PORT_MAP} 
    env_file: .env
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  web:
    build: .
    env_file: .env
    command: bundle exec rails s -p ${PORT} -b '0.0.0.0'
    ports:
      - ${PORT}:${PORT} 
    depends_on:
      - db
volumes:
  pgdata:
