version: '3'
services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - ${DB_PORT_MAP}
    env_file: .env
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    expose:
      - '5432'
  web:
    build: .
    env_file: .env
    command: bundle exec rails s -p ${PORT} -b '0.0.0.0'
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - ./log:/myapp/log
      - ./public/assets:/myapp/public/assets
volumes:
  pgdata:
