default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: db
  password:
  pool: 5

development:
  <<: *default
  database: wp_dev

test:
  <<: *default
  database: myapp_test
