default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: db
  username: postgres
  password:
  database: myapp_development

test:
  <<: *default
  host: db
  password:
  database: myapp_test
  username: postgres

production:
  <<: *default
  database: WakePatternProd
  username: WakePattern
  password: futurama543
  host: wakepatternprod.cvyu4ku1saus.us-west-2.rds.amazonaws.com
  port: 5432
