default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["PG_HOST"] %>
  password:
  pool: 5

development:
  <<: *default
  username: postgres
  database: wp_dev

test:
  <<: *default
  username: postgres
  database: wp_test

production:
  <<: *default
  username: postgres
  database: wakepattern_prod
